name: CI/CD

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
          # Temporary use old version of Doxygen https://github.com/urho3d/Urho3D/issues/2757
          do { choco install --no-progress doxygen.install } until ($?)
          do { choco install --no-progress llvm --version=6.0.1 --allow-downgrade } until ($?)
          do { choco install --no-progress ninja } until ($?)
    - name: Configure and Build
      shell: cmd
      run: |
        git submodule update
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        mkdir build
        cd build
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE:STRING="Release" ..
        cmake --build . --config Release
      
